shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('categorias/<int:categoria_id>/', views.mostrar_categoria, name='mostrar_categoria'),
    path('subcategorias/<int:subcategoria_id>/', views.mostrar_subcategoria, name='mostrar_subcategoria'),
    path('productos/<int:producto_id>/', views.mostrar_producto, name='mostrar_producto'),
    path('buscar_productos/', views.buscar_productos, name='buscar_productos'),
    path('logout/', views.logout_view, name='logout'),
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('ver_carrito/', views.ver_carrito, name='ver_carrito'),
    path('cambiar_cantidad/<int:item_id>/<str:action>/', views.cambiar_cantidad, name='cambiar_cantidad'),
    path('profile/', views.profile, name='profile'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('signup/', views.CustomSignupView.as_view(), name='signup'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('shop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

shop/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='categorias/', null=True, blank=True)

    def __str__(self):
        return self.nombre

class Subcategoria(models.Model):
    nombre = models.CharField(max_length=100)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    stock = models.IntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    especificaciones_tecnicas = models.TextField(blank=True, null=True)
    subcategoria = models.ForeignKey(Subcategoria, on_delete=models.CASCADE, blank=True, null=True)
    imagen = models.ImageField(upload_to='productos/', null=True, blank=True)

    def save(self, *args, **kwargs):
        # Verificar si el objeto ya tiene un ID asignado
        if not self.id:
            # Obtener el máximo ID existente y agregar 1
            max_id = Producto.objects.aggregate(models.Max('id'))['id__max']
            self.id = max_id + 1 if max_id else 1

        super().save(*args, **kwargs)

    def obtener_especificaciones(self):
        if self.especificaciones_tecnicas:
            return self.especificaciones_tecnicas.split(',')
        else:
            return []

    def __str__(self):
        return self.nombre

class Tutorial(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

class Comentario(models.Model):
    texto = models.TextField()
    fecha_hora = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.usuario.username} - {self.producto.nombre}'

class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    productos = models.ManyToManyField('Producto', through='ItemCarrito')
    creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Carrito {self.id}'
    
class ItemCarrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'Item: {self.producto.nombre} - Cantidad: {self.cantidad}'

class MetodoPago(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

shop/forms.py
from django import forms

class AgregarAlCarritoForm(forms.Form):
    cantidad = forms.IntegerField(min_value=1)

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import redirect
from .models import *
import random
from django.http import JsonResponse
from random import sample
from django.contrib.auth.decorators import login_required
from django.contrib.auth.signals import user_logged_in
from allauth.account.views import LoginView, SignupView

# Create your views here.
def index(request):
    # Obtén todas las categorías y subcategorías de la base de datos
    categorias = Categoria.objects.all()
    subcategorias = Subcategoria.objects.all()

    # Obtén todos los productos de la base de datos
    todos_los_productos = Producto.objects.all()

    # Obtener el carrito actual del usuario o crear uno nuevo
    carrito_id = request.session.get('carrito_id')
    if carrito_id:
        try:
            carrito = Carrito.objects.get(id=carrito_id)
        except Carrito.DoesNotExist:
            carrito = None
    else:
        carrito = None

    # Seleccionar una muestra aleatoria de productos destacados
    productos_destacados = random.sample(list(todos_los_productos), min(6, len(todos_los_productos)))

    return render(request, 'index.html', {'categorias': categorias, 'subcategorias': subcategorias, 'carrito': carrito, 'productos_destacados': productos_destacados})


@login_required
def profile(request):
    # Obtener la información del usuario autenticado
    user = request.user
    # Puedes agregar más detalles según tus necesidades, como el nombre, la dirección, etc.

    return render(request, 'profile.html', {'user': user})

def logout_view(request):
    logout(request)
    return redirect('shop:index')

class CustomLoginView(LoginView):
    template_name = 'socialaccount/login.html'

class CustomSignupView(SignupView):
    template_name = 'socialaccount/signup.html'
    


def mostrar_categoria(request, categoria_id):
    # Obtener la categoría seleccionada desde la base de datos
    categoria = get_object_or_404(Categoria, id=categoria_id)
    # Obtener todas las subcategorías asociadas a la categoría seleccionada
    subcategorias = categoria.subcategoria_set.all()

    # Pasa los datos a la plantilla 'categoria.html'
    return render(request, 'categoria.html', {'categoria': categoria, 'subcategorias': subcategorias})

def mostrar_subcategoria(request, subcategoria_id):
    # Obtener la subcategoría seleccionada desde la base de datos
    subcategoria = get_object_or_404(Subcategoria, id=subcategoria_id)
    # Obtener todos los productos asociados a la subcategoría seleccionada
    productos = subcategoria.producto_set.all()

    # Pasa los datos a la plantilla 'categoria.html'
    return render(request, 'categoria.html', {'categoria': subcategoria.categoria, 'subcategorias': subcategoria.categoria.subcategoria_set.all(), 'productos': productos})

def mostrar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    subcategoria_productos = Producto.objects.filter(subcategoria=producto.subcategoria).order_by('id')

    # Obtener el índice del producto actual en la lista
    current_index = list(subcategoria_productos).index(producto)

    # Obtener el producto anterior y siguiente si existen
    producto_anterior = subcategoria_productos[current_index - 1] if current_index > 0 else None
    producto_siguiente = subcategoria_productos[current_index + 1] if current_index < len(subcategoria_productos) - 1 else None

    # Obtener productos relacionados al azar (excepto el producto actual) y elegir hasta 3
    productos_relacionados = random.sample(list(subcategoria_productos.exclude(id=producto.id)), min(5, subcategoria_productos.count() - 1))

    context = {
        'producto': producto,
        'producto_anterior': producto_anterior,
        'producto_siguiente': producto_siguiente,
        'productos_relacionados': productos_relacionados,
    }

    return render(request, 'producto.html', context)

def buscar_productos(request):
    query = request.GET.get('q')

    if query:
        # Realiza la búsqueda de productos que coincidan con la consulta
        productos = Producto.objects.filter(nombre__icontains=query)
    else:
        productos = []

    return render(request, 'buscar_producto.html', {'query': query, 'productos': productos})


def agregar_al_carrito(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)

    # Obtener el carrito del usuario autenticado si está logueado
    carrito_autenticado = None
    if request.user.is_authenticated:
        carrito_autenticado, _ = Carrito.objects.get_or_create(usuario=request.user)

        # Verificar si el producto ya existe en el carrito del usuario autenticado
        item_carrito_autenticado = carrito_autenticado.itemcarrito_set.filter(producto=producto).first()
        if item_carrito_autenticado:
            # Actualizar la cantidad si ya existe
            if item_carrito_autenticado.cantidad < producto.stock:
                item_carrito_autenticado.cantidad += 1
                item_carrito_autenticado.save()
            return JsonResponse({'cantidad': item_carrito_autenticado.cantidad})

    # Obtener el carrito de la sesión actual del usuario o crear uno nuevo
    carrito_id = request.session.get('carrito_id')
    if carrito_id:
        try:
            carrito = Carrito.objects.get(id=carrito_id)
        except Carrito.DoesNotExist:
            carrito = None
    else:
        carrito = None

    if not carrito:
        carrito = Carrito.objects.create(usuario=None)  # No se asocia con un usuario
        request.session['carrito_id'] = carrito.id

    if producto.stock > 0:
        # Verificar si el usuario está autenticado
        if request.user.is_authenticated:
            # Transferir productos del carrito no autenticado al carrito del usuario autenticado
            if carrito.itemcarrito_set.exists():
                for item in carrito.itemcarrito_set.all():
                    item.carrito = carrito_autenticado
                    item.save()
            carrito.delete()  # Eliminar el carrito no autenticado

            # Obtener el carrito actual del usuario autenticado
            carrito = carrito_autenticado

        item_carrito, created = ItemCarrito.objects.get_or_create(carrito=carrito, producto=producto)

        # Restricción de cantidad máxima basada en el stock
        max_cantidad_permitida = min(producto.stock, 30)
        if not created:
            if item_carrito.cantidad < max_cantidad_permitida:
                item_carrito.cantidad += 1
                item_carrito.save()
        else:
            item_carrito.cantidad = 1
            item_carrito.save()

        return JsonResponse({'cantidad': item_carrito.cantidad})

    return JsonResponse({})


def transferir_carrito(sender, user, request, **kwargs):
    carrito_no_autenticado = None
    carrito_autenticado = None

    # Obtener el carrito no autenticado si existe
    carrito_id = request.session.get('carrito_id')
    if carrito_id:
        try:
            carrito_no_autenticado = Carrito.objects.get(id=carrito_id)
        except Carrito.DoesNotExist:
            carrito_no_autenticado = None

    # Obtener el carrito del usuario autenticado
    carrito_autenticado, _ = Carrito.objects.get_or_create(usuario=user)

    # Transferir productos del carrito no autenticado al carrito del usuario autenticado
    if carrito_no_autenticado and carrito_no_autenticado.itemcarrito_set.exists():
        for item in carrito_no_autenticado.itemcarrito_set.all():
            item.carrito = carrito_autenticado
            item.save()

        carrito_no_autenticado.delete()  # Eliminar el carrito no autenticado

user_logged_in.connect(transferir_carrito)


# def clear_carrito_session(sender, user, request, **kwargs):
#     if 'carrito_id' in request.session:
#         del request.session['carrito_id']

# user_logged_in.connect(clear_carrito_session)


def ver_carrito(request):
    usuario = request.user
    carrito_autenticado = None
    carrito_no_autenticado = None
    subtotal_items = []
    total = 0

    # Obtener el carrito autenticado si el usuario está logueado
    if usuario.is_authenticated:
        carrito_autenticado, _ = Carrito.objects.get_or_create(usuario=usuario)

    # Obtener el carrito no autenticado si existe en la sesión
    carrito_id = request.session.get('carrito_id')
    if carrito_id:
        try:
            carrito_no_autenticado = Carrito.objects.get(id=carrito_id)
        except Carrito.DoesNotExist:
            carrito_no_autenticado = None

    # Si hay un carrito autenticado, agregar sus productos al subtotal y total
    if carrito_autenticado:
        for item in carrito_autenticado.itemcarrito_set.all():
            subtotal = item.cantidad * item.producto.precio
            subtotal_items.append((item, subtotal))
            total += subtotal

    # Si hay un carrito no autenticado, agregar sus productos al subtotal y total
    if carrito_no_autenticado:
        for item in carrito_no_autenticado.itemcarrito_set.all():
            subtotal = item.cantidad * item.producto.precio
            subtotal_items.append((item, subtotal))
            total += subtotal

    return render(request, 'carrito.html', {'carrito': carrito_autenticado, 'carrito_no_autenticado': carrito_no_autenticado, 'subtotal_items': subtotal_items, 'total': total})


def cambiar_cantidad(request, item_id, action):
    if request.method == 'GET' and request.is_ajax():
        item_carrito = ItemCarrito.objects.get(id=item_id)
        if action == 'sumar':
            if item_carrito.cantidad < item_carrito.producto.stock:
                item_carrito.cantidad += 1
                item_carrito.save()
                return JsonResponse({'success': True})
        elif action == 'restar':
            if item_carrito.cantidad > 1:
                item_carrito.cantidad -= 1
                item_carrito.save()

shop/templates/already_logged_in.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="alert alert-info text-center" role="alert">
                <h4 class="alert-heading">¡Hola, {{ user.username }}!</h4>
                <p class="mb-0">Ya estás logueado con tu cuenta de Google: {{ social_account.extra_data.email }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/base.html
{% load socialaccount %}
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - CODIGO SAC.</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- Enlace al archivo base.css -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet" />
    <!-- Enlace al archivo categoria.css -->
    <link href="{% static 'css/categoria.css' %}" rel="stylesheet" />
    <!-- Enlace al archivo producto.css -->
    <link href="{% static 'css/producto.css' %}" rel="stylesheet" />
    <!-- Agrega los enlaces CSS de Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>
    <div class="container-fluid bg-primary py-2 encabezado-buscadores">
        <!-- Buscador y Login -->
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-8">
                    <form class="d-flex" method="get" action="{% url 'shop:buscar_productos' %}">
                        <div class="input-group">
                            <input class="form-control form-control-lg" type="search" name="q" id="search-input"
                                placeholder="Buscar productos..." aria-label="Search" autocomplete="off">
                            <button class="btn btn-primary btn-lg btn-search" type="submit">
                                <i class="bi-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
                <div class="col-md-4 text-end">
                    {% if user.is_authenticated %}
                    <!-- Si el usuario está autenticado, muestra la foto y el nombre del usuario -->
                    <div class="dropdown">
                        <a class="btn btn-custom-login dropdown-toggle" href="#" role="button" id="userDropdown"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if user.socialaccount_set.first %}
                                <img src="{{ user.socialaccount_set.first.get_avatar_url }}" alt="User Avatar"
                                    class="rounded-circle me-1" style="width: 24px; height: 24px;">
                            {% else %}
                                <img src="{% static 'image/login.png' %}" alt="Default Avatar"
                                    class="rounded-circle me-1" style="width: 24px; height: 24px;">
                            {% endif %}
                            {{ user.username|title }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                            <li><a class="dropdown-item" href="{% url 'shop:profile' %}">My Account</a></li>
                            <li><a class="dropdown-item" href="{% url 'shop:logout' %}">Logout</a></li>
                        </ul>
                    </div>
                    {% else %}
                    <!-- Si el usuario no está autenticado, muestra el enlace de inicio de sesión -->
                    <a href="{% provider_login_url 'google' %}" class="btn btn-primary">Login</a>
                    {% endif %}
                </div>                
            </div>
        </div>
    </div>

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="/">CODIGO SAC.</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <!-- Lista de Categorías y Subcategorías -->
                    <li class="nav-item dropdown dropdown-hover">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">Productos</a>
                        <ul class="dropdown-menu multi-column columns-3" aria-labelledby="navbarDropdown">
                            <div class="row">
                                {% for categoria in categorias %}
                                <div class="col">
                                    <li><a class="dropdown-item"
                                            href="{% url 'shop:mostrar_categoria' categoria.id %}">{{categoria.nombre|upper}}</a>
                                    </li>
                                    {% for subcategoria in categoria.subcategoria_set.all %}
                                    <li><a class="dropdown-item"
                                            href="{% url 'shop:mostrar_subcategoria' subcategoria.id %}">{{subcategoria.nombre}}</a>
                                    </li>
                                    {% endfor %}
                                </div>
                                {% endfor %}
                            </div>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="#!">Tutoriales</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">Quienes somos</a></li>
                </ul>
                <form class="d-flex">
                    <a class="btn btn-outline-light me-2" href="{% url 'shop:ver_carrito' %}">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span id="carrito-cantidad-badge" class="badge bg-light text-dark ms-1 rounded-pill">{{ carrito_cantidad }}</span>
                    </a>
                </form>                
            </div>
        </div>
    </nav>

    <main style="margin: 15px 0;">
        <!-- Contenido específico de cada página -->
        {% block content %}
        {% endblock %}
    </main>

    <!-- Pie de página -->
    <footer class="bg-dark text-white py-4">
        <div class="container">
            <div class="row">
                <!-- Columna de información de contacto -->
                <div class="col-md-4 mb-3">
                    <h5>Contacto</h5>
                    <p><i class="bi bi-geo-alt-fill"></i> Dirección: Calle Principal, Ciudad, País</p>
                    <p><i class="bi bi-telephone-fill"></i> Teléfono: +123 456 7890</p>
                    <p><i class="bi bi-envelope-fill"></i> Correo electrónico: info@example.com</p>
                </div>
                <!-- Columna de enlaces importantes -->
                <div class="col-md-4 mb-3">
                    <h5>Enlaces</h5>
                    <ul class="list-unstyled">
                        <li><a class="text-white" href="/">Inicio</a></li>
                        <li><a class="text-white" href="#!">Productos</a></li>
                        <li><a class="text-white" href="#!">Ofertas</a></li>
                        <li><a class="text-white" href="#!">Contacto</a></li>
                    </ul>
                </div>
                <!-- Columna de redes sociales -->
                <div class="col-md-4 mb-3">
                    <h5>Redes Sociales</h5>
                    <ul class="list-inline">
                        <li class="list-inline-item"><a class="text-white" href="#!"><i class="bi bi-facebook"></i></a>
                        </li>
                        <li class="list-inline-item"><a class="text-white" href="#!"><i class="bi bi-twitter"></i></a>
                        </li>
                        <li class="list-inline-item"><a class="text-white" href="#!"><i class="bi bi-instagram"></i></a>
                        </li>
                        <li class="list-inline-item"><a class="text-white" href="#!"><i class="bi bi-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- Créditos y derechos de autor -->
        <div class="container text-center mt-3">
            <p class="m-0">© 2023 Tu Sitio Web | Todos los derechos reservados</p>
        </div>
    </footer>

    <!-- Bootstrap core JS y otros scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/search.js' %}"></script>
    <!-- Agrega el script de Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-aAf0km2dsGfoM6q9qYbi3BZpAR5vLrWgkwr3r7h1G9pJcuYy1H8FKNZlVU0l3RM0"
        crossorigin="anonymous"></script>

</body>

</html>

shop/templates/buscar_producto.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2>Resultados de búsqueda para "{{ query }}"</h2>
    {% if productos %}
    <div class="row">
        {% for producto in productos %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 border rounded shadow">
                <!-- Product image -->
                <div class="position-relative" style="height: 200px; overflow: hidden;">
                    <img class="card-img-top img-fluid" src="{{ producto.imagen.url }}"
                        alt="{{ producto.nombre }}" style="object-fit: cover; width: 100%; height: 100%;" />
                </div>
                <hr class="my-3">
                <!-- Product details -->
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'shop:mostrar_producto' producto.id %}"
                            class="text-decoration-none">{{ producto.nombre }}</a></h5>
                    <hr class="my-3">
                    <h2 class="card-text h5">S/. {{ producto.precio }}</h2>
                    <a class="btn btn-outline-primary mt-3" href="{% url 'shop:mostrar_producto' producto.id %}"
                        style="width: 100%;">Ver detalles</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-info mt-5" role="alert">
        <h4 class="alert-heading">"Lo sentimos, no se encontraron resultados que coincidan con tu búsqueda."</h4>
        <p class="mb-0">Realiza la búsqueda de otro producto.</p>
    </div>
    {% endif %}
</div>
{% endblock %}

shop/templates/categoria.html
{% extends 'base.html' %}

{% block content %}
<div class="container categoria">
    <div class="row">
        <!-- Columna para mostrar las subcategorías -->
        <div class="col-md-3">
            <h2>{{ categoria.nombre }}</h2>
            <div class="list-group">
                {% for subcategoria in subcategorias %}
                <a href="{% url 'shop:mostrar_subcategoria' subcategoria.id %}"
                    class="list-group-item list-group-item-action">{{ subcategoria.nombre }}</a>
                {% endfor %}
            </div>
        </div>
        <!-- Columna para mostrar las subcategorías y productos de la categoría seleccionada -->
        <div class="col-md-9">
            {% if subcategorias %}
            <h2 class="mb-4">Subcategorías</h2>
            <div class="row">
                {% for subcategoria in subcategorias %}
                <div class="col-md-6 mb-4">
                    <div class="card h-100 border-primary rounded">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'shop:mostrar_subcategoria' subcategoria.id %}"
                                    class="text-decoration-none stretched-link">{{ subcategoria.nombre }}</a></h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            {% if productos %}
            <h2 class="mb-4 mt-5">Productos</h2>
            <hr class="mb-4">
            <div class="row">
                {% for producto in productos %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100 border rounded shadow">
                        <!-- Product image-->
                        <div class="position-relative" style="height: 300px; overflow: hidden;">
                            <img class="card-img-top img-fluid" src="{{ producto.imagen.url }}"
                                alt="{{ producto.nombre }}" style="object-fit: cover; width: 100%; height: 100%;" />
                        </div>
                        <hr class="my-3">
                        <!-- Product details-->
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'shop:mostrar_producto' producto.id %}"
                                    class="text-decoration-none">{{ producto.nombre }}</a></h5>
                            <hr class="my-3">
                            <h2 class="card-text h5">S/. {{ producto.precio }}</h2>
                            <hr class="my-3">
                            {% if producto.stock > 0 %}
                            <p class="card-text text-success">Stock disponible: {{ producto.stock }}</p>
                            <a class="btn btn-outline-primary mt-3" href="{% url 'shop:mostrar_producto' producto.id %}"
                                style="width: 100%;">Ver detalles</a>
                            <a class="btn btn-primary mt-2 agregar-carrito" href="#"
                                data-producto-id="{{ producto.id }}" style="width: 100%;">Agregar al carrito <i
                                    class="bi bi-cart"></i></a>
                            {% else %}

                            <p class="card-text text-danger">Agotado</p>
                            <a class="btn btn-outline-primary mt-3" href="{% url 'shop:mostrar_producto' producto.id %}"
                                style="width: 100%;">Ver detalles</a>
                            <a class="btn btn-primary mt-2 disabled" href="#" style="width: 100%;"
                                aria-disabled="true">Agregar al carrito <i class="bi bi-cart"></i></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="alert alert-info mt-5" role="alert">
                <h4 class="alert-heading">¡Ups! No hay productos disponibles.</h4>
                <p class="mb-0">Selecciona una subcategoría para ver los productos disponibles.</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<script>
    // Función para enviar una solicitud AJAX al servidor para agregar el producto al carrito
function agregarAlCarrito(productoId) {
    fetch(`/agregar_al_carrito/${productoId}/`, {
        method: 'POST',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}', // Agregar el token CSRF a la solicitud
            'Content-Type': 'application/json'
        }
    })
    .then(response => response.json())
    .then(data => {
        // Almacena la cantidad en el LocalStorage
        localStorage.setItem('carrito_cantidad', data.cantidad);
        // Recargar la página para actualizar el stock
        location.reload();
    });
}

// Manejar el clic en el botón "Agregar al carrito"
const agregarCarritoButtons = document.querySelectorAll('.agregar-carrito');
agregarCarritoButtons.forEach(button => {
    button.addEventListener('click', function(event) {
        event.preventDefault();
        const productoId = this.dataset.productoId;
        agregarAlCarrito(productoId);
    });
});

</script>


{% endblock %}